// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: asset.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listAssets = `-- name: ListAssets :many
SELECT id, filename, mime_type, size_bytes, r2_key, width, height, created_at, deleted_at FROM asset WHERE deleted_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListAssets(ctx context.Context) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.MimeType,
			&i.SizeBytes,
			&i.R2Key,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAsset = `-- name: SoftDeleteAsset :exec
UPDATE asset SET deleted_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteAsset(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteAsset, id)
	return err
}

const upsertAsset = `-- name: UpsertAsset :one
INSERT INTO asset (filename, mime_type, size_bytes, r2_key, width, height)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (r2_key) DO UPDATE
SET filename   = EXCLUDED.filename,
    mime_type  = EXCLUDED.mime_type,
    size_bytes = EXCLUDED.size_bytes,
    width      = EXCLUDED.width,
    height     = EXCLUDED.height
RETURNING id, filename, mime_type, size_bytes, r2_key, width, height, created_at, deleted_at
`

type UpsertAssetParams struct {
	Filename  string      `json:"filename"`
	MimeType  string      `json:"mime_type"`
	SizeBytes int64       `json:"size_bytes"`
	R2Key     string      `json:"r2_key"`
	Width     pgtype.Int4 `json:"width"`
	Height    pgtype.Int4 `json:"height"`
}

func (q *Queries) UpsertAsset(ctx context.Context, arg UpsertAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, upsertAsset,
		arg.Filename,
		arg.MimeType,
		arg.SizeBytes,
		arg.R2Key,
		arg.Width,
		arg.Height,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.MimeType,
		&i.SizeBytes,
		&i.R2Key,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
