// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blog_series.sql

package store

import (
	"context"
)

const getBlogSeriesBySlug = `-- name: GetBlogSeriesBySlug :one
SELECT id, slug, name, description, created_at FROM blog_series WHERE slug = $1
`

func (q *Queries) GetBlogSeriesBySlug(ctx context.Context, slug string) (BlogSeries, error) {
	row := q.db.QueryRow(ctx, getBlogSeriesBySlug, slug)
	var i BlogSeries
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const upsertBlogSeries = `-- name: UpsertBlogSeries :one
INSERT INTO blog_series (slug, name, description)
VALUES ($1, $2, $3)
ON CONFLICT (slug) DO UPDATE
SET name        = EXCLUDED.name,
    description = EXCLUDED.description
RETURNING id, slug, name, description, created_at
`

type UpsertBlogSeriesParams struct {
	Slug        string `json:"slug"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) UpsertBlogSeries(ctx context.Context, arg UpsertBlogSeriesParams) (BlogSeries, error) {
	row := q.db.QueryRow(ctx, upsertBlogSeries, arg.Slug, arg.Name, arg.Description)
	var i BlogSeries
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
