// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blog_post.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const linkBlogPostTag = `-- name: LinkBlogPostTag :exec
INSERT INTO blog_post_tags (blog_post_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LinkBlogPostTagParams struct {
	BlogPostID pgtype.UUID `json:"blog_post_id"`
	TagID      pgtype.UUID `json:"tag_id"`
}

func (q *Queries) LinkBlogPostTag(ctx context.Context, arg LinkBlogPostTagParams) error {
	_, err := q.db.Exec(ctx, linkBlogPostTag, arg.BlogPostID, arg.TagID)
	return err
}

const listBlogPosts = `-- name: ListBlogPosts :many
SELECT id, slug, title, excerpt, body, cover_asset_id, series_id, series_order, published_at, created_at, updated_at FROM blog_post
WHERE published_at IS NOT NULL
ORDER BY published_at DESC
`

func (q *Queries) ListBlogPosts(ctx context.Context) ([]BlogPost, error) {
	rows, err := q.db.Query(ctx, listBlogPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BlogPost{}
	for rows.Next() {
		var i BlogPost
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Excerpt,
			&i.Body,
			&i.CoverAssetID,
			&i.SeriesID,
			&i.SeriesOrder,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBlogPost = `-- name: UpsertBlogPost :one
INSERT INTO blog_post (slug, title, excerpt, body, cover_asset_id, series_id, series_order, published_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (slug) DO UPDATE
SET title          = EXCLUDED.title,
    excerpt        = EXCLUDED.excerpt,
    body           = EXCLUDED.body,
    cover_asset_id = EXCLUDED.cover_asset_id,
    series_id      = EXCLUDED.series_id,
    series_order   = EXCLUDED.series_order,
    published_at   = EXCLUDED.published_at,
    updated_at     = now()
RETURNING id, slug, title, excerpt, body, cover_asset_id, series_id, series_order, published_at, created_at, updated_at
`

type UpsertBlogPostParams struct {
	Slug         string             `json:"slug"`
	Title        string             `json:"title"`
	Excerpt      string             `json:"excerpt"`
	Body         string             `json:"body"`
	CoverAssetID pgtype.UUID        `json:"cover_asset_id"`
	SeriesID     pgtype.UUID        `json:"series_id"`
	SeriesOrder  pgtype.Int4        `json:"series_order"`
	PublishedAt  pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) UpsertBlogPost(ctx context.Context, arg UpsertBlogPostParams) (BlogPost, error) {
	row := q.db.QueryRow(ctx, upsertBlogPost,
		arg.Slug,
		arg.Title,
		arg.Excerpt,
		arg.Body,
		arg.CoverAssetID,
		arg.SeriesID,
		arg.SeriesOrder,
		arg.PublishedAt,
	)
	var i BlogPost
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Excerpt,
		&i.Body,
		&i.CoverAssetID,
		&i.SeriesID,
		&i.SeriesOrder,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
