// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: experience.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listExperience = `-- name: ListExperience :many
SELECT id, company, role, location, start_date, end_date, description, sort_order, created_at FROM experience ORDER BY sort_order DESC, start_date DESC
`

func (q *Queries) ListExperience(ctx context.Context) ([]Experience, error) {
	rows, err := q.db.Query(ctx, listExperience)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Experience{}
	for rows.Next() {
		var i Experience
		if err := rows.Scan(
			&i.ID,
			&i.Company,
			&i.Role,
			&i.Location,
			&i.StartDate,
			&i.EndDate,
			&i.Description,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExperience = `-- name: UpsertExperience :one
INSERT INTO experience (company, role, location, start_date, end_date, description, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (company, role, start_date) DO UPDATE
SET location    = EXCLUDED.location,
    end_date    = EXCLUDED.end_date,
    description = EXCLUDED.description,
    sort_order  = EXCLUDED.sort_order
RETURNING id, company, role, location, start_date, end_date, description, sort_order, created_at
`

type UpsertExperienceParams struct {
	Company     string      `json:"company"`
	Role        string      `json:"role"`
	Location    string      `json:"location"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
	Description string      `json:"description"`
	SortOrder   int32       `json:"sort_order"`
}

func (q *Queries) UpsertExperience(ctx context.Context, arg UpsertExperienceParams) (Experience, error) {
	row := q.db.QueryRow(ctx, upsertExperience,
		arg.Company,
		arg.Role,
		arg.Location,
		arg.StartDate,
		arg.EndDate,
		arg.Description,
		arg.SortOrder,
	)
	var i Experience
	err := row.Scan(
		&i.ID,
		&i.Company,
		&i.Role,
		&i.Location,
		&i.StartDate,
		&i.EndDate,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}
