// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Asset struct {
	ID        pgtype.UUID        `json:"id"`
	Filename  string             `json:"filename"`
	MimeType  string             `json:"mime_type"`
	SizeBytes int64              `json:"size_bytes"`
	R2Key     string             `json:"r2_key"`
	Width     pgtype.Int4        `json:"width"`
	Height    pgtype.Int4        `json:"height"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type BlogPost struct {
	ID              pgtype.UUID        `json:"id"`
	Slug            string             `json:"slug"`
	Title           string             `json:"title"`
	Excerpt         string             `json:"excerpt"`
	Body            string             `json:"body"`
	CoverAssetID    pgtype.UUID        `json:"cover_asset_id"`
	SeriesID        pgtype.UUID        `json:"series_id"`
	SeriesOrder     pgtype.Int4        `json:"series_order"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ReadingTimeMins int32              `json:"reading_time_mins"`
	CoverUrl        string             `json:"cover_url"`
	OgImageUrl      string             `json:"og_image_url"`
}

type BlogPostTag struct {
	BlogPostID pgtype.UUID `json:"blog_post_id"`
	TagID      pgtype.UUID `json:"tag_id"`
}

type BlogSeries struct {
	ID          pgtype.UUID        `json:"id"`
	Slug        string             `json:"slug"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Experience struct {
	ID          pgtype.UUID        `json:"id"`
	Company     string             `json:"company"`
	Role        string             `json:"role"`
	Location    string             `json:"location"`
	StartDate   pgtype.Date        `json:"start_date"`
	EndDate     pgtype.Date        `json:"end_date"`
	Description string             `json:"description"`
	SortOrder   int32              `json:"sort_order"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Profile struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Headline  string             `json:"headline"`
	Bio       string             `json:"bio"`
	Location  string             `json:"location"`
	Email     string             `json:"email"`
	ResumeUrl pgtype.Text        `json:"resume_url"`
	AvatarUrl pgtype.Text        `json:"avatar_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Project struct {
	ID           pgtype.UUID        `json:"id"`
	Slug         string             `json:"slug"`
	Title        string             `json:"title"`
	Tagline      string             `json:"tagline"`
	Summary      string             `json:"summary"`
	BodyOverview string             `json:"body_overview"`
	BodyWhyBuilt string             `json:"body_why_built"`
	BodyLearning string             `json:"body_learning"`
	CoverAssetID pgtype.UUID        `json:"cover_asset_id"`
	RepoUrl      pgtype.Text        `json:"repo_url"`
	LiveUrl      pgtype.Text        `json:"live_url"`
	SortOrder    int32              `json:"sort_order"`
	PublishedAt  pgtype.Timestamptz `json:"published_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Featured     bool               `json:"featured"`
	CoverUrl     string             `json:"cover_url"`
}

type ProjectTag struct {
	ProjectID pgtype.UUID `json:"project_id"`
	TagID     pgtype.UUID `json:"tag_id"`
}

type SocialLink struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Url       string             `json:"url"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Tag struct {
	ID        pgtype.UUID        `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Testimonial struct {
	ID            pgtype.UUID        `json:"id"`
	AuthorName    string             `json:"author_name"`
	AuthorRole    string             `json:"author_role"`
	AuthorCompany string             `json:"author_company"`
	Quote         string             `json:"quote"`
	AvatarAssetID pgtype.UUID        `json:"avatar_asset_id"`
	SortOrder     int32              `json:"sort_order"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Visible       bool               `json:"visible"`
}
