// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProfile = `-- name: GetProfile :one
SELECT id, name, headline, bio, location, email, resume_url, avatar_url, created_at, updated_at FROM profile LIMIT 1
`

func (q *Queries) GetProfile(ctx context.Context) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfile)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Headline,
		&i.Bio,
		&i.Location,
		&i.Email,
		&i.ResumeUrl,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProfile = `-- name: UpsertProfile :one
INSERT INTO profile (name, headline, bio, location, email, resume_url, avatar_url)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (email) DO UPDATE
SET name       = EXCLUDED.name,
    headline   = EXCLUDED.headline,
    bio        = EXCLUDED.bio,
    location   = EXCLUDED.location,
    resume_url = EXCLUDED.resume_url,
    avatar_url = EXCLUDED.avatar_url,
    updated_at = now()
RETURNING id, name, headline, bio, location, email, resume_url, avatar_url, created_at, updated_at
`

type UpsertProfileParams struct {
	Name      string      `json:"name"`
	Headline  string      `json:"headline"`
	Bio       string      `json:"bio"`
	Location  string      `json:"location"`
	Email     string      `json:"email"`
	ResumeUrl pgtype.Text `json:"resume_url"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

// Singleton: keyed by email so re-running the seed updates the existing row.
func (q *Queries) UpsertProfile(ctx context.Context, arg UpsertProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, upsertProfile,
		arg.Name,
		arg.Headline,
		arg.Bio,
		arg.Location,
		arg.Email,
		arg.ResumeUrl,
		arg.AvatarUrl,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Headline,
		&i.Bio,
		&i.Location,
		&i.Email,
		&i.ResumeUrl,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
