// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const linkProjectTag = `-- name: LinkProjectTag :exec
INSERT INTO project_tags (project_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LinkProjectTagParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	TagID     pgtype.UUID `json:"tag_id"`
}

func (q *Queries) LinkProjectTag(ctx context.Context, arg LinkProjectTagParams) error {
	_, err := q.db.Exec(ctx, linkProjectTag, arg.ProjectID, arg.TagID)
	return err
}

const listProjects = `-- name: ListProjects :many
SELECT id, slug, title, tagline, summary, body_overview, body_why_built, body_learning, cover_asset_id, repo_url, live_url, sort_order, published_at, created_at, updated_at FROM project
WHERE published_at IS NOT NULL
ORDER BY sort_order, published_at DESC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Tagline,
			&i.Summary,
			&i.BodyOverview,
			&i.BodyWhyBuilt,
			&i.BodyLearning,
			&i.CoverAssetID,
			&i.RepoUrl,
			&i.LiveUrl,
			&i.SortOrder,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProject = `-- name: UpsertProject :one
INSERT INTO project (
    slug, title, tagline, summary,
    body_overview, body_why_built, body_learning,
    cover_asset_id, repo_url, live_url,
    sort_order, published_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (slug) DO UPDATE
SET title          = EXCLUDED.title,
    tagline        = EXCLUDED.tagline,
    summary        = EXCLUDED.summary,
    body_overview  = EXCLUDED.body_overview,
    body_why_built = EXCLUDED.body_why_built,
    body_learning  = EXCLUDED.body_learning,
    cover_asset_id = EXCLUDED.cover_asset_id,
    repo_url       = EXCLUDED.repo_url,
    live_url       = EXCLUDED.live_url,
    sort_order     = EXCLUDED.sort_order,
    published_at   = EXCLUDED.published_at,
    updated_at     = now()
RETURNING id, slug, title, tagline, summary, body_overview, body_why_built, body_learning, cover_asset_id, repo_url, live_url, sort_order, published_at, created_at, updated_at
`

type UpsertProjectParams struct {
	Slug         string             `json:"slug"`
	Title        string             `json:"title"`
	Tagline      string             `json:"tagline"`
	Summary      string             `json:"summary"`
	BodyOverview string             `json:"body_overview"`
	BodyWhyBuilt string             `json:"body_why_built"`
	BodyLearning string             `json:"body_learning"`
	CoverAssetID pgtype.UUID        `json:"cover_asset_id"`
	RepoUrl      pgtype.Text        `json:"repo_url"`
	LiveUrl      pgtype.Text        `json:"live_url"`
	SortOrder    int32              `json:"sort_order"`
	PublishedAt  pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) UpsertProject(ctx context.Context, arg UpsertProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, upsertProject,
		arg.Slug,
		arg.Title,
		arg.Tagline,
		arg.Summary,
		arg.BodyOverview,
		arg.BodyWhyBuilt,
		arg.BodyLearning,
		arg.CoverAssetID,
		arg.RepoUrl,
		arg.LiveUrl,
		arg.SortOrder,
		arg.PublishedAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Tagline,
		&i.Summary,
		&i.BodyOverview,
		&i.BodyWhyBuilt,
		&i.BodyLearning,
		&i.CoverAssetID,
		&i.RepoUrl,
		&i.LiveUrl,
		&i.SortOrder,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
