// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT
    p.slug,
    p.title,
    p.tagline,
    p.summary,
    p.body_overview,
    p.body_why_built,
    p.body_learning,
    p.repo_url,
    p.live_url,
    p.published_at,
    a.r2_key AS cover_key,
    COALESCE(
        array_agg(t.name ORDER BY t.name) FILTER (WHERE t.id IS NOT NULL),
        '{}'
    )::text[] AS tags
FROM project p
LEFT JOIN asset a       ON a.id = p.cover_asset_id AND a.deleted_at IS NULL
LEFT JOIN project_tags pt ON pt.project_id = p.id
LEFT JOIN tag t         ON t.id = pt.tag_id
WHERE p.slug = $1
  AND p.published_at IS NOT NULL
GROUP BY p.id, a.r2_key
`

type GetProjectBySlugRow struct {
	Slug         string             `json:"slug"`
	Title        string             `json:"title"`
	Tagline      string             `json:"tagline"`
	Summary      string             `json:"summary"`
	BodyOverview string             `json:"body_overview"`
	BodyWhyBuilt string             `json:"body_why_built"`
	BodyLearning string             `json:"body_learning"`
	RepoUrl      pgtype.Text        `json:"repo_url"`
	LiveUrl      pgtype.Text        `json:"live_url"`
	PublishedAt  pgtype.Timestamptz `json:"published_at"`
	CoverKey     pgtype.Text        `json:"cover_key"`
	Tags         []string           `json:"tags"`
}

// Powers the project detail page. Returns the full project (all three markdown
// body sections, repo/live links, meta) plus the cover asset key and the
// aggregated tag names so the page builds in a single round trip. Only
// published projects are visible to the public site.
func (q *Queries) GetProjectBySlug(ctx context.Context, slug string) (GetProjectBySlugRow, error) {
	row := q.db.QueryRow(ctx, getProjectBySlug, slug)
	var i GetProjectBySlugRow
	err := row.Scan(
		&i.Slug,
		&i.Title,
		&i.Tagline,
		&i.Summary,
		&i.BodyOverview,
		&i.BodyWhyBuilt,
		&i.BodyLearning,
		&i.RepoUrl,
		&i.LiveUrl,
		&i.PublishedAt,
		&i.CoverKey,
		&i.Tags,
	)
	return i, err
}

const linkProjectTag = `-- name: LinkProjectTag :exec
INSERT INTO project_tags (project_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LinkProjectTagParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	TagID     pgtype.UUID `json:"tag_id"`
}

func (q *Queries) LinkProjectTag(ctx context.Context, arg LinkProjectTagParams) error {
	_, err := q.db.Exec(ctx, linkProjectTag, arg.ProjectID, arg.TagID)
	return err
}

const listProjectCards = `-- name: ListProjectCards :many
SELECT
    p.slug,
    p.title,
    p.summary,
    a.r2_key AS cover_key,
    COALESCE(
        array_agg(t.name ORDER BY t.name) FILTER (WHERE t.id IS NOT NULL),
        '{}'
    )::text[] AS tags
FROM project p
LEFT JOIN asset a       ON a.id = p.cover_asset_id AND a.deleted_at IS NULL
LEFT JOIN project_tags pt ON pt.project_id = p.id
LEFT JOIN tag t         ON t.id = pt.tag_id
WHERE p.published_at IS NOT NULL
  AND (NOT $1::boolean OR p.featured = true)
GROUP BY p.id, a.r2_key
ORDER BY p.sort_order, p.published_at DESC
LIMIT $2
`

type ListProjectCardsParams struct {
	FeaturedOnly bool  `json:"featured_only"`
	RowLimit     int32 `json:"row_limit"`
}

type ListProjectCardsRow struct {
	Slug     string      `json:"slug"`
	Title    string      `json:"title"`
	Summary  string      `json:"summary"`
	CoverKey pgtype.Text `json:"cover_key"`
	Tags     []string    `json:"tags"`
}

// Powers the homepage "featured work" strip and the projects index. Joins the
// cover asset (nullable) and aggregates the project's tag names into a single
// text[] so the handler builds each card in one round trip. When featured_only
// is true the result is limited to projects flagged for the homepage.
func (q *Queries) ListProjectCards(ctx context.Context, arg ListProjectCardsParams) ([]ListProjectCardsRow, error) {
	rows, err := q.db.Query(ctx, listProjectCards, arg.FeaturedOnly, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectCardsRow{}
	for rows.Next() {
		var i ListProjectCardsRow
		if err := rows.Scan(
			&i.Slug,
			&i.Title,
			&i.Summary,
			&i.CoverKey,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, slug, title, tagline, summary, body_overview, body_why_built, body_learning, cover_asset_id, repo_url, live_url, sort_order, published_at, created_at, updated_at, featured FROM project
WHERE published_at IS NOT NULL
ORDER BY sort_order, published_at DESC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Tagline,
			&i.Summary,
			&i.BodyOverview,
			&i.BodyWhyBuilt,
			&i.BodyLearning,
			&i.CoverAssetID,
			&i.RepoUrl,
			&i.LiveUrl,
			&i.SortOrder,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Featured,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProject = `-- name: UpsertProject :one
INSERT INTO project (
    slug, title, tagline, summary,
    body_overview, body_why_built, body_learning,
    cover_asset_id, repo_url, live_url,
    sort_order, featured, published_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
ON CONFLICT (slug) DO UPDATE
SET title          = EXCLUDED.title,
    tagline        = EXCLUDED.tagline,
    summary        = EXCLUDED.summary,
    body_overview  = EXCLUDED.body_overview,
    body_why_built = EXCLUDED.body_why_built,
    body_learning  = EXCLUDED.body_learning,
    cover_asset_id = EXCLUDED.cover_asset_id,
    repo_url       = EXCLUDED.repo_url,
    live_url       = EXCLUDED.live_url,
    sort_order     = EXCLUDED.sort_order,
    featured       = EXCLUDED.featured,
    published_at   = EXCLUDED.published_at,
    updated_at     = now()
RETURNING id, slug, title, tagline, summary, body_overview, body_why_built, body_learning, cover_asset_id, repo_url, live_url, sort_order, published_at, created_at, updated_at, featured
`

type UpsertProjectParams struct {
	Slug         string             `json:"slug"`
	Title        string             `json:"title"`
	Tagline      string             `json:"tagline"`
	Summary      string             `json:"summary"`
	BodyOverview string             `json:"body_overview"`
	BodyWhyBuilt string             `json:"body_why_built"`
	BodyLearning string             `json:"body_learning"`
	CoverAssetID pgtype.UUID        `json:"cover_asset_id"`
	RepoUrl      pgtype.Text        `json:"repo_url"`
	LiveUrl      pgtype.Text        `json:"live_url"`
	SortOrder    int32              `json:"sort_order"`
	Featured     bool               `json:"featured"`
	PublishedAt  pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) UpsertProject(ctx context.Context, arg UpsertProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, upsertProject,
		arg.Slug,
		arg.Title,
		arg.Tagline,
		arg.Summary,
		arg.BodyOverview,
		arg.BodyWhyBuilt,
		arg.BodyLearning,
		arg.CoverAssetID,
		arg.RepoUrl,
		arg.LiveUrl,
		arg.SortOrder,
		arg.Featured,
		arg.PublishedAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Tagline,
		&i.Summary,
		&i.BodyOverview,
		&i.BodyWhyBuilt,
		&i.BodyLearning,
		&i.CoverAssetID,
		&i.RepoUrl,
		&i.LiveUrl,
		&i.SortOrder,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Featured,
	)
	return i, err
}
