// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: social_link.sql

package store

import (
	"context"
)

const listSocialLinks = `-- name: ListSocialLinks :many
SELECT id, name, url, sort_order, created_at FROM social_link ORDER BY sort_order
`

func (q *Queries) ListSocialLinks(ctx context.Context) ([]SocialLink, error) {
	rows, err := q.db.Query(ctx, listSocialLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SocialLink{}
	for rows.Next() {
		var i SocialLink
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSocialLink = `-- name: UpsertSocialLink :one
INSERT INTO social_link (name, url, sort_order)
VALUES ($1, $2, $3)
ON CONFLICT (name) DO UPDATE
SET url        = EXCLUDED.url,
    sort_order = EXCLUDED.sort_order
RETURNING id, name, url, sort_order, created_at
`

type UpsertSocialLinkParams struct {
	Name      string `json:"name"`
	Url       string `json:"url"`
	SortOrder int32  `json:"sort_order"`
}

func (q *Queries) UpsertSocialLink(ctx context.Context, arg UpsertSocialLinkParams) (SocialLink, error) {
	row := q.db.QueryRow(ctx, upsertSocialLink, arg.Name, arg.Url, arg.SortOrder)
	var i SocialLink
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}
