// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package store

import (
	"context"
)

const getAdminStats = `-- name: GetAdminStats :one
SELECT
    (SELECT COUNT(*) FROM blog_post)                                AS total_posts,
    (SELECT COUNT(*) FROM blog_post WHERE published_at IS NOT NULL) AS published_posts,
    (SELECT COUNT(*) FROM blog_post WHERE published_at IS NULL)     AS draft_posts,
    (SELECT COUNT(*) FROM project)                                  AS total_projects
`

type GetAdminStatsRow struct {
	TotalPosts     int64 `json:"total_posts"`
	PublishedPosts int64 `json:"published_posts"`
	DraftPosts     int64 `json:"draft_posts"`
	TotalProjects  int64 `json:"total_projects"`
}

// Dashboard counts for the admin overview (GET /api/v1/admin/stats). There is
// no status column on blog_post: a post is "published" when published_at IS NOT
// NULL and a "draft" otherwise. Projects are surfaced as a single total.
func (q *Queries) GetAdminStats(ctx context.Context) (GetAdminStatsRow, error) {
	row := q.db.QueryRow(ctx, getAdminStats)
	var i GetAdminStatsRow
	err := row.Scan(
		&i.TotalPosts,
		&i.PublishedPosts,
		&i.DraftPosts,
		&i.TotalProjects,
	)
	return i, err
}
