// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: testimonial.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listTestimonials = `-- name: ListTestimonials :many
SELECT id, author_name, author_role, author_company, quote, avatar_asset_id, sort_order, created_at FROM testimonial ORDER BY sort_order
`

func (q *Queries) ListTestimonials(ctx context.Context) ([]Testimonial, error) {
	rows, err := q.db.Query(ctx, listTestimonials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Testimonial{}
	for rows.Next() {
		var i Testimonial
		if err := rows.Scan(
			&i.ID,
			&i.AuthorName,
			&i.AuthorRole,
			&i.AuthorCompany,
			&i.Quote,
			&i.AvatarAssetID,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTestimonial = `-- name: UpsertTestimonial :one
INSERT INTO testimonial (author_name, author_role, author_company, quote, avatar_asset_id, sort_order)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (author_name, quote) DO UPDATE
SET author_role     = EXCLUDED.author_role,
    author_company  = EXCLUDED.author_company,
    avatar_asset_id = EXCLUDED.avatar_asset_id,
    sort_order      = EXCLUDED.sort_order
RETURNING id, author_name, author_role, author_company, quote, avatar_asset_id, sort_order, created_at
`

type UpsertTestimonialParams struct {
	AuthorName    string      `json:"author_name"`
	AuthorRole    string      `json:"author_role"`
	AuthorCompany string      `json:"author_company"`
	Quote         string      `json:"quote"`
	AvatarAssetID pgtype.UUID `json:"avatar_asset_id"`
	SortOrder     int32       `json:"sort_order"`
}

func (q *Queries) UpsertTestimonial(ctx context.Context, arg UpsertTestimonialParams) (Testimonial, error) {
	row := q.db.QueryRow(ctx, upsertTestimonial,
		arg.AuthorName,
		arg.AuthorRole,
		arg.AuthorCompany,
		arg.Quote,
		arg.AvatarAssetID,
		arg.SortOrder,
	)
	var i Testimonial
	err := row.Scan(
		&i.ID,
		&i.AuthorName,
		&i.AuthorRole,
		&i.AuthorCompany,
		&i.Quote,
		&i.AvatarAssetID,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}
